# enables renovate-bot to run pre-commit hooks
# https://github.com/balena-io/renovate-config/blob/master/.github/renovate.json#L3
# https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/pre-commit/readme.md
# https://pre-commit.com/#intro
---
repos:
- repo: local
  hooks:
    - id: build-flowzone-yaml
      name: expand YAML anchors
      entry: npm run build
      # https://pre-commit.com/#node
      language: node
