name: Protect branch
description: Apply branch protection rules
inputs:
  github_token:
    description: A personal access token for the GitHub service account wirh admin/owner permissions.
    required: true
  required_approving_review_count:
    description: Setting this value to zero effectively means merge==deploy without approval(s).
    required: true

outputs:
  result:
    description: Result of GitHub API operation
    value: ${{ steps.apply_branch_protection_rules.outputs.result }}

runs:
  using: composite

  steps:
    - shell: bash
      id: apply_branch_protection_rules
      run: |
        url='${{ github.api_url }}/repos/${{ github.repository }}/branches/${{ github.event.repository.default_branch }}/protection'

        result="$(curl --silent -X PUT "${url}" \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ inputs.github_token }}' \
          -d '{
          "required_status_checks": {
            "strict": true,
            "contexts": [
              "Flowzone / Checks",
              "Flowzone / NPM",
              "Flowzone / Docker",
              "VersionBot/generate-version"
            ]
          },
          "enforce_admins": false,
          "required_pull_request_reviews": {
            "dismissal_restrictions": {
              "users": [],
              "teams": []
            },
            "dismiss_stale_reviews": false,
            "require_code_owner_reviews": false,
            "required_approving_review_count": ${{ required_approving_review_count }},
            "bypass_pull_request_allowances": {
              "users": [],
              "teams": []
            }
          },
          "restrictions": null,
          "required_linear_history": false,
          "allow_force_pushes": false,
          "allow_deletions": false,
          "block_creations": false,
          "required_conversation_resolution": false
        }')"

        echo ::set-output name=result::"${result}"
