name: 'VersionBot'
description: 'Apply opinionated versioning to a branch'
inputs:
  default_repo_type:
    description: 'Default repo type if repo.yml is not found'
    required: false
    default: 'generic'
  author_email:
    description: 'Author email for the versioned git commit'
    required: false
    default: 'flowzone@users.noreply.github.com'
  author_name:
    description: 'Author name for the versioned git commit'
    required: false
    default: 'Flowzone'
  github_token:
    description: 'A Personal Access Token for the GitHub service account.'
    required: true
outputs:
  version:
    description: "The project's version after running versionist"
    value: ${{ steps.versionist.outputs.version }}

runs:
  using: "composite"

  steps:

    # TODO: finalize existing draft npm and docker releases

    # run an up-to-date fork of the balena-versionist action
    # - name: Run versionist
    #   id: versionist
    #   uses: klutchell/versionist@v0.5.0
    #   with:
    #     github_email: '${{ inputs.author_email }}'
    #     github_username: '${{ inputs.author_name }}'
    #     github_token: '${{ inputs.github_token }}'
    #     branch: '${{ inputs.branch }}'

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # TODO: rewrite this action to be a nodejs project
    - id: versionist
      shell: bash
      run: |
        npm install --location=global versionist@v6.7.1 balena-versionist@v0.14.5
        git config --global user.email "${{ inputs.author_email }}"
        git config --global user.name "${{ inputs.author_name }}"
        jq '.type' repo.yml 2>/dev/null || echo "type: ${{ inputs.default_repo_type }}" > repo.yml
        balena-versionist --silent=false
        VERSION="v$(head -n1 VERSION || jq -r '.version' package.json)"
        echo "::set-output name=version::${VERSION}"
        git add -A
        git commit -m "${VERSION}"
        git tag -a "${VERSION}" -m "${VERSION}"
        git push origin HEAD:${{ github.head_ref || github.ref }} --follow-tags
