# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Publish custom"
description: "Custom publish step to run after all tests have passed"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Dump context
      shell: bash
      env:
        GITHUB: ${{ toJSON(github) }}
        INPUTS: ${{ inputs.json }}
        SECRETS: ${{ inputs.secrets }}
        VARIABLES: ${{ toJSON(inputs.variables) }}
      run: |
        echo "${GITHUB}"
        echo "${INPUTS}"
        echo "${SECRETS}"
        echo "${VARIABLES}"

    - name: Create artifact
      id: artifact
      shell: bash
      run: |
        path="$(mktemp)"
        echo "Hello, World!" > "${path}"
        echo "path=${path}" >> "${GITHUB_OUTPUT}"

    # Test publishing release artifacts to github
    - name: Upload generated flowzone.yml
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
      with:
        name: gh-release-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}-${{ strategy.job-index }}
        path: ${{ steps.artifact.outputs.path }}
        retention-days: 1
