# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Publish custom"
description: "Custom publish step to run after all tests have passed"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Dump context
      shell: bash
      env:
        GITHUB: ${{ toJSON(github) }}
        INPUTS: ${{ inputs.json }}
        SECRETS: ${{ inputs.secrets }}
        VARIABLES: ${{ toJSON(inputs.variables) }}
      run: |
        echo "${GITHUB}"
        echo "${INPUTS}"
        echo "${SECRETS}"
        echo "${VARIABLES}"

    - name: Check for GitHub App private key
      id: gh_app_private_key
      shell: bash
      run: |
        if [ -n '${{ fromJSON(inputs.secrets).GH_APP_PRIVATE_KEY }}' ]
        then
          echo 'found=true' >> $GITHUB_OUTPUT
        else
          echo 'found=false' >> $GITHUB_OUTPUT
        fi

    # https://github.com/marketplace/actions/github-app-token
    - name: Generate GitHub App installation token
      uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f # v2.0.0
      if: steps.gh_app_private_key.outputs.found == 'true'
      id: gh_app_installation_token
      with:
        app_id: ${{ fromJSON(inputs.json).app_id }}
        installation_id: ${{ fromJSON(inputs.json).installation_id }}
        private_key: ${{ fromJSON(inputs.secrets).GH_APP_PRIVATE_KEY }}
        permissions: ${{ fromJSON(inputs.json).token_scope }}

    # Test publishing release artifacts to github
    - name: Upload generated flowzone.yml
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
      with:
        name: gh-release-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
        path: .github/workflows/flowzone.yml
        retention-days: 1
