# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Always custom"
description: "Custom step to run always"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Dump context
      shell: bash
      env:
        GITHUB: ${{ toJSON(github) }}
        INPUTS: ${{ inputs.json }}
        SECRETS: ${{ inputs.secrets }}
        VARIABLES: ${{ toJSON(inputs.variables) }}
      run: |
        echo "${GITHUB}"
        echo "${INPUTS}"
        echo "${SECRETS}"
        echo "${VARIABLES}"

    # https://github.com/marketplace/actions/github-app-token
    - name: Generate GitHub App installation token
      uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f # v2.0.0
      id: gh_app_installation_token
      with:
        app_id: ${{ fromJSON(inputs.json).app_id }}
        installation_retrieval_mode: id
        installation_retrieval_payload: ${{ fromJSON(inputs.json).installation_id }}
        private_key: ${{ fromJSON(inputs.secrets).GH_APP_PRIVATE_KEY }}
        permissions: ${{ fromJSON(inputs.json).token_scope }}
