on:
  workflow_call:

jobs:
  check_type:
    runs-on: 'ubuntu-latest'
    # Declare outputs for next jobs
    outputs:
      type: ${{ steps.check_type.outputs.type }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the check
          fetch-depth: 1
      - shell: pwsh
        id: check_type
        run: |
          if test -f "package.json"; then
              echo "found package.json"
              Write-Host "::set-output name=docs_changed::nodejs"
          fi

  build_node:
    name: Test NodeJS 16.x
    runs-on: ubuntu-latest
    needs: [check_type]
    if: needs.check_type.outputs.docs_changed == 'nodejs'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
