on:
  workflow_call:
    secrets:
      FLOWZONE_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASS:
        required: true
      BALENA_API_KEY_PUSH:
        required: true
      BALENA_API_KEY_TEST:
        required: false
      COMPOSE_VARS:
        required: false
    inputs:
      working_directory:
        description: 'Github actions working directory'
        type: string
        required: false
        default: '.'

jobs:

  versionbot:
    name: VersionBot
    runs-on: ubuntu-latest
    # only run on PR merges to the default branch and skip events triggered by versionbot
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch && !contains(github.event.head_commit.author.name, 'VersionBot') }}

    outputs:
      version: ${{ steps.versionbot.outputs.version }}
      updated: ${{ steps.versionbot.outputs.updated }}

    steps:

      # checkout must happen in flowzone in order for local composite action path to exist
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          # check out full depth for changelog generation
          fetch-depth: 0
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - name: Run VersionBot
        id: versionbot
        uses: ./.github/actions/versionbot
        with:
          github_token: '${{ secrets.FLOWZONE_TOKEN }}'

  check_type:
    name: Check Project Type
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' && github.base_ref == github.event.repository.default_branch }}

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    # Declare outputs for next jobs
    outputs:
      npm: ${{ steps.check_type.outputs.npm }}
      sut: ${{ steps.check_type.outputs.sut }}

    steps:

      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the check
          fetch-depth: 1
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - shell: bash
        id: check_type
        run: |
          if test -f "package.json"; then
            echo "found package.json"
            echo ::set-output name=npm::"True"
          else
            echo ::set-output name=npm::"False"
          fi

          if [ -f docker-compose.test.yml ] && [ -f docker-compose.yml ]; then
            echo "found docker-compose.test.yml"
            echo ::set-output name=sut::"True"
          else
            echo ::set-output name=sut::"False"
          fi

  npm_test:
    name: Test NodeJS 16.x
    runs-on: ubuntu-latest
    needs: [check_type]
    if: needs.check_type.outputs.npm == 'True'

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:

      - id: versionbot_checkout
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'versionbot/pr/${{ github.event.pull_request.number }}'
          fetch-depth: 1
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - if: ${{ steps.versionbot_checkout.outcome == 'failure' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - name: Run NPM test
        id: docker
        uses: ./.github/actions/npm
        with:
          working_directory: ${{ inputs.working_directory }}
          node_version: '16.x'

  sut_test:
    name: Test with docker compose
    runs-on: ubuntu-latest
    needs: [check_type]
    if: needs.check_type.outputs.sut == 'True'

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    env:
      COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}

    steps:

      - id: versionbot_checkout
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'versionbot/pr/${{ github.event.pull_request.number }}'
          fetch-depth: 1
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - if: ${{ steps.versionbot_checkout.outcome == 'failure' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: '${{ secrets.FLOWZONE_TOKEN }}'

      - name: Run Docker test
        id: docker
        uses: ./.github/actions/docker
        with:
          working_directory: ${{ inputs.working_directory }}
