name: Tests

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./tests
