name: Tests

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  push:
    tags:
      - v*.*.*

jobs:
  flowzone:
    name: Flowzone
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./tests
      required_approving_review_count: 0
      verbose: true
      balena_slugs: |
        product_os/flowzone-aarch64
        product_os/flowzone-amd64
        product_os/flowzone-armv7hf
