name: Tests

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./tests
      required_approving_review_count: 0
      docker_platforms: |
        linux/amd64
        linux/aarch64
