name: Test

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:
  # Test npm projects using the sample code in ./npm
  npm_test:
    name: NPM test
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./npm

  # Test npm projects using the sample code in ./docker-compose
  docker_compose_test:
    name: Docker compose test
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./docker-compose
