name: Tests

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./tests
      required_approving_review_count: 0
